#!/bin/bash

# try to get specific WAL file from src_hosts in cycle
set -e

error_handler() {
    scriptname=$(basename $0)
    hostname=$(hostname)
    echo "^^^ ERROR at [host: '${hostname}', file: '${scriptname}', line: '${BASH_LINENO[0]}']"
}
trap error_handler ERR

saved_args=( "$@" )
saved_self_name=$0
pmax=4
local_dir=/var/local/WALs  # for putting wal manually
only_local=                # use WALs only from local_dir, do not read it from NFS

src_hosts="$1" # ssh hosts
buffer_dir=/var/lib/postgresql/wals_buffer      # first load file by ssh here, not tmpfs

tmp_dir='/lib/init/rw/pg_recv_sb'               # file with error counter, created by puppet, tmpfs

cmd_timeout="6"
ssh_timeout_options="-o ConnectTimeout=10 -o ServerAliveInterval=6 -o ServerAliveCountMax=5"
ssh_options="-o Compression=no -c aes128-gcm@openssh.com -o BatchMode=yes ${ssh_timeout_options}"
ssh_master_socket='/tmp/ssh_%h_%p_%r'
ssh_master_options='-o ControlMaster=auto -o ControlPersist=yes'
use_ssh_persist=yes

src_dir="$2"
fname="$3"
dst_file="$4"    # always 'pg_xlog/RECOVERYXLOG'
delay_time="$5"  # wal apply delay

retry_count="6"     # see below
cooldown_time="600" # do not try to catch file from host for a '$cooldown_time' seconds after $retry_count attemps

if [ -f /etc/default/restore_cmd ]; then
    . /etc/default/restore_cmd
fi

if [ -n "$use_ssh_persist" ]; then
    ssh_options="$ssh_options -o ControlPath=$ssh_master_socket $ssh_master_options"
fi

if [ -z "$src_hosts" -o -z "$src_dir" -o -z "$fname" -o -z "$dst_file" ]; then
    echo -e "usage: restore_cmd 'SRC-HOSTNAMES' SRC-DIR SRC-WAL-FILENAME DST-WAL-FILENAME-WITH-PATH [DELAY-SECONDS]\n" \
	"\n" \
	"SRC-HOSTNAMES              - two archive host names in single quotes\n" \
	"SRC-DIR                    - archive directory with WALs\n" \
	"SRC-WAL-FILENAME           - %f (file name)\n" \
	"DST-WAL-FILENAME-WITH-PATH - %p (file name with path)\n" \
	"DELAY-SECONDS              - copy WAL file only if it older than this seconds\n"
    exit 1
fi

decompress() {
    local dst_file=$1
    mime=$(file -m /etc/postgresql-common/compress.mime.mgc -b --mime-type "$dst_file")
    if [ "$mime" = "application/x-bzip2" ]; then
        pbzip2 -p"$pmax" -d < "$dst_file" > "$dst_file".bz2-tmp || { decompress_error=$?; return 1; }
        mv "$dst_file".bz2-tmp "$dst_file"
    elif [ "$mime" = "application/x-gzip" ]; then
        gunzip < "$dst_file" > "$dst_file".gz-tmp || { decompress_error=$?; return 1; }
        mv "$dst_file".gz-tmp "$dst_file"
    fi
}

# decides whether to apply current wal from buffer or not
apply_wal() {
    local received_from=$1
    local src_dir=$2
    local fname=$3
    local dst_file=$4
    local decompress_error

    if [ "$delay_time" ] && [ "$delay_time" -gt 0 ]; then
        ftime="$(stat -c %Y "$src_dir"/"$fname")"
        apply_time="$(date --date="now - $delay_time seconds" +%s)"
        if [ "$ftime" -gt "$apply_time" ]; then
            # file is too new, skip it, replay it only after $delay_time seconds
            # show message only sometimes
            if [ $(( (ftime - apply_time) % (10 * 60) )) -lt 3 ]; then
                echo "file '$fname' is too new ($((ftime - apply_time))s), skip it"
            fi
            exit 1
        fi
    fi

    mv "$src_dir"/"$fname" "$dst_file"
    decompress_error=''
    if ! decompress "$dst_file"; then
        # dst_file can be "destroyed" during decompress,
        # that's why ignore possible error when delete it
        rm "$dst_file" || true

        # if error, try another host, only if it is not local operation
        # not local_dir or buffer_dir
        if (( decompress_error )) && [[ $received_from ]]; then
            if [[ $RESTORE_CMD_TRY_OTHER ]]; then
                echo "ERROR: cannot unpack wal from all hosts"
                exit 1
            fi

            # reexec and try other server
            echo "WARNING: decompress error from host $received_from, trying other"
            RESTORE_CMD_TRY_OTHER=$received_from \
                exec "$saved_self_name" "${saved_args[@]}"
        else
            # mv error or something unknown
            echo "ERROR: decompress error"
            exit 1
        fi
    fi
}

if [ -d "$local_dir" ] && [ -f "$local_dir"/"$fname" ]; then
    src_dir="$local_dir"
fi

if ! [ -d "$buffer_dir" ]; then
    mkdir -p "$buffer_dir"
fi

# check that wal file exists and its size is not zero
if [ -s "$buffer_dir"/"$fname" ]; then
    src_dir="$buffer_dir"
fi

if [ "$only_local" ] && [ "$src_dir" != "$local_dir" ]; then
    # src_dir set to local_dir above, if not - requested WAL file does not exist in local_dir, exit now
    exit 1
fi

# take wal from 'special local dir' or 'ssh buffer dir'
if [ "$src_dir" = "$local_dir" ] || [ "$src_dir" = "$buffer_dir" ]; then
    apply_wal "$src_dir" "$fname" "$dst_file"
    exit 0
fi

src_hosts_count=$(wc -w <<< $src_hosts)

# fetch wal via ssh to buffer dir
fetch_errors=0 # any receiving wal errors
conn_errors=0  # only ssh transfer errors
for host in $src_hosts ; do
    # if it is retry and this is the host from which corrupted wal had been received, then try another host
    if [[ $RESTORE_CMD_TRY_OTHER && $host = $RESTORE_CMD_TRY_OTHER ]]; then
        fetch_errors=$(($fetch_errors + 1))
        continue
    fi

    # check if retry is nedeed for that host
    if [ -f "${tmp_dir}/ssh-errors_${host}_" ]; then
        # if not reached $retry_count limit, then continue to read from that host
        was_failed_cnt=$(<"${tmp_dir}/ssh-errors_${host}_")
        if [ "$was_failed_cnt" -lt "$retry_count" ]; then
            true
        # reaching $retry_count retries limit, stop try to read wal from that host during $cooldown_time seconds
        else
            now_time=$(date +%s)
            last_err_time=$(stat -c%Y "${tmp_dir}/ssh-errors_${host}_")
            if [[ $(( $now_time - $last_err_time)) -le $cooldown_time ]]; then
                fetch_errors=$(($fetch_errors + 1))
                # try to read from next host
                continue
            # repeat again trying after $cooldown_time, with setting counter of errors to 0
            else
                rm "${tmp_dir}/ssh-errors_${host}_"
            fi
        fi
    fi

    # read by ssh
    # in case of error, empty file will be created (!)
    set +e
    timeout ${cmd_timeout} ssh ${ssh_options} ${host} \
        "test -f '$src_dir'/'$fname' && cat '$src_dir'/'$fname' || exit 148" \
                      > "$buffer_dir"/"$fname".part
    ssh_code=$?
    set -e
    # if successfully get file then exit
    if [ "$ssh_code" -eq "0" ]; then
        # in case of success, set error counter value to 0 by removing file with counter
        [ -f "${tmp_dir}/ssh-errors_${host}_" ] && rm "${tmp_dir}/ssh-errors_${host}_"
        mv "$buffer_dir"/"$fname".part "$buffer_dir"/"$fname"
        break;
    # file still not exist on archive server
    elif [ "$ssh_code" -eq "148" ]; then
        echo "WARNING: can't find wal '$fname' at host '$host'"
        # zero the file-counter, as connection is restored
        [ -f "${tmp_dir}/ssh-errors_${host}_" ] && rm "${tmp_dir}/ssh-errors_${host}_"
        fetch_errors=$(($fetch_errors + 1))
        # delete empty temp file
        test -f "$buffer_dir"/"$fname".part && rm "$buffer_dir"/"$fname".part
    # all other exit codes are considered to be connection error
    else
        echo "WARNING: connection error, can't fetch wal '$fname' from host '$host'"
        fetch_errors=$(($fetch_errors + 1))
        conn_errors=$(($conn_errors + 1))

        # increment counter of connection errors
        if [ -f "${tmp_dir}/ssh-errors_${host}_" ]; then
            failed_cnt=$(<"${tmp_dir}/ssh-errors_${host}_")
            failed_cnt=$(( failed_cnt + 1 ))
            echo "$failed_cnt" > "${tmp_dir}/ssh-errors_${host}_"
        else
            echo 1 > "${tmp_dir}/ssh-errors_${host}_"
        fi
        # remove empty temp file (size 0)
        test -f "$buffer_dir"/"$fname".part && rm "$buffer_dir"/"$fname".part
    fi
done
received_from=$host

# if can't connect to both hosts, then remove files counters of errors,
# so as not to "fall asleep" in vain and for a long time
if [ "$conn_errors" -ge "$src_hosts_count" ]; then
    for host in $src_hosts ; do
        if [ -f "${tmp_dir}/ssh-errors_${host}_" ]; then
            rm "${tmp_dir}/ssh-errors_${host}_"
        fi
    done
fi

if [ "$fetch_errors" -ge "$src_hosts_count" ]; then
    echo "ERROR: can't fetch wal from all hosts: ${src_hosts}"
    exit 1
fi

apply_wal "$received_from" "$buffer_dir" "$fname" "$dst_file"

exit 0

