#!/bin/bash

set -e
pmax=4
remote_cmd=/usr/local/bin/archive_remote_cmd
ssh_options="-o Compression=no -c aes128-gcm@openssh.com -o BatchMode=yes"
ssh_master_socket='/tmp/ssh_%h_%p_%r'
ssh_master_options='-o ControlMaster=auto -o ControlPersist=yes'
use_ssh_persist=
remote_compress=
send_status=
pwals=5
ready_wals_for_parallel=10   # ready wals должен быть, как минимум, в два раза больше, чем pwals ?

unset LANG LANGUAGE LC_ALL LC_CTYPE LC_COLLATE LC_MESSAGES LC_TIME LC_NUMERIC
export LC_ALL=C
 
if [ -f /etc/default/archive_cmd ]; then
    . /etc/default/archive_cmd
fi

if [ -n "$use_ssh_persist" ]; then
    ssh_options="$ssh_options -S $ssh_master_socket $ssh_master_options"
fi

dst_host="$1"
dst_dir="$2"
log_dir="$dst_dir"/../
src_file="$3"
fname="$4"
src_dir=${src_file%/$fname}
arch_status_dir="$src_dir"/archive_status

if [ -z "$dst_host" -o -z "$dst_dir" -o -z "$src_file" -o -z "$fname" ]; then
    echo -e "usage: archive_cmd DST-HOSTNAME DST-DIR SRC-WAL-FILENAME-WITH-PATH SRC-WAL-FILENAME\n" \
	"\n" \
	"DST-HOSTNAME               - for scp\n" \
	"DST-DIR                    - archive directory for WALs\n" \
	"SRC-WAL-FILENAME-WITH-PATH - %p (file name with path)\n" \
	"SRC-WAL-FILENAME           - %f (file name)\n"
    exit 1
fi

set -o pipefail

# проверяет является ли имя файла именем wal
is_wal() {
    local fname="$1"
    if [[ "$fname" == ???????????????????????? ]] && [[ "$fname" != *.* ]]; then
        return 0 # zero is true
    else
        return 1 # non-zero is false
    fi
}

# отправляет файл на standby по ssh
send_wal() {
    local fname_with_path="$1"
    local file_name="$2"
    ftime=$(stat -c %y "$fname_with_path")
    # проверить и архивировать только WAL, backup label и history пропускать без архивации
    if [[ "$file_name" == ???????????????????????? && -z "$remote_compress" ]]; then
        pbzip2 -1 -p"$pmax" < "$fname_with_path"
    else
        cat "$fname_with_path"
    fi \
        | ssh $ssh_options "$dst_host" "$remote_cmd" "$dst_dir" "$file_name" "'$ftime'" "'$remote_compress'" "$pmax" "'$send_status'"
    /usr/local/bin/vmtouch -q -e "$fname_with_path"
}

# проверим не отправлялся ли такой файл уже в архив
if [[ -r ${log_dir}/LASTLOG ]]; then
    prev_archived=$(< ${log_dir}/LASTLOG)
else
    prev_archived=""
fi
# файлы вида '000000010004EF04000000E1.00010DF0.backup' и '00000015.history' архивируем всегда
# сравниваем только wal
# если предыдущий заархивированный файл не wal - архивируем в один поток (для корректного сравнения '<')
if is_wal "$fname" && is_wal "$prev_archived"; then
    if [[ "$fname" < "$prev_archived" ]] || [[ "$fname" = "$prev_archived" ]]; then
        echo "File '$fname' was already sent to archive. Skipping..."
        exit 0
    fi
fi

# нужно ли выполнить параллельное архивирование?
ready_count=$(find ${arch_status_dir}/ -maxdepth 1 -type f -name "????????????????????????.ready" | wc -l)

# архивируем в один поток если:
# - число готовых к архивации wal меньше порога ready_wals_for_parallel
# - файл не является wal (.backup, .history)
# - предыдущий заархивированный файл не является wal
if [[ $ready_count -le $ready_wals_for_parallel ]] || ! is_wal "$fname" || ! is_wal "$prev_archived"; then
    send_wal "$src_file" "$fname"
    wal=$fname
else
    # запускаем параллельное архивирвоание

    # возьем pwals файлов
    ready_wals=$(find ${arch_status_dir}/ -maxdepth 1 -type f -name "????????????????????????.ready" -printf '%f\n'\
                        | sort | grep -A "$(( pwals - 1 ))" -F ${fname})

    # отправим эти wal параллельно
    declare -A send_pids
    for wal_ready in $ready_wals ; do
        wal=${wal_ready%.ready}
        send_wal "$src_dir"/"$wal" "$wal" & send_pids[$wal]=$!
    done

    # обработаем все коды выхода каждого потока
    for wal_pid in ${!send_pids[@]}; do
        exit_code=0
        wait ${send_pids[$wal_pid]} || exit_code=$?
        if [[ $exit_code -ne 0 ]] ; then
            echo "ERROR: can't send '$wal_pid' to archive. Exit code: '$exit_code'"
            exit 1
        fi
    done
fi

echo "$wal" > "$log_dir"/LASTLOG

exit 0
